### ISSUE TITLE
No path output

### ISSUE THREAD

**Issue by Petopp** [bcluzel/pypath#1]
Hi,
Unfortunately I don't get any path data back when I run this code. What am I doing wrong?

thank you

Petop

`
from pypath import*

field = Field(width_mm=300,height_mm=300,robot_diameter_mm=30)

castar = Castar()

err, path = castar.find_path_simplified(start_coordinates=Coordinates(200,200), end_coordinates=Coordinates(50,50), field=field)

print (path)
print (err)
`

**Comment by bcluzel** [comment]
Hi!
Well, if the constructor take in input dimensions in mm, the methods use cm.
It's not homogeneous at all and will be probably fixed later.
So for now use it like this:
```python
field = Field(width_mm=3000,height_mm=3000,robot_diameter_mm=300)

castar = Castar()

err, path = castar.find_path_simplified(start_coordinates=Coordinates(200,200), end_coordinates=Coordinates(50,50), field=field)
```

And then you got the path.
In fact you are going to have just the last node because there is no obstacle between the start and the end.
